In [ ]:
import pandas as pd
# The data is publicly available, on https://dataverse.unc.edu/dataset.xhtml?persistentId=doi:10.15139/S3/11900&version=3.3
# I choose not to put the data in this public repo for licensing reasons.
data_dir = "/home/llinfeng/Dropbox/Research/Data/AddHealth/WaveI/"

Supposedly, the WaveI data with n=55208 is under restricted access. Yet, it takes $1,000 to buy into the contract for restricted access.

In [6]:
df_net = pd.read_sas(data_dir + "w1network.sas7bdat")
df_net.filter(like="EGO").shape

# Note, problem here: there should 55208, by Table 1 in Bramoull√© et. al. 2009. Only 6504 here.

Warning: column count mismatch (108 + 255 != 439)

/home/llinfeng/.local/lib/python3.9/site-packages/pandas/io/sas/sas7bdat.py:800: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  rslt[name] = self._byte_chunk[jb, :].view(dtype=self.byte_order + "d")

(6504, 0)

In [6]:
df_net = pd.read_sas(data_dir + "w1network.sas7bdat")
df_net.filter(like="EGO").shape

Warning: column count mismatch (108 + 255 != 439)

/home/llinfeng/.local/lib/python3.9/site-packages/pandas/io/sas/sas7bdat.py:800: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  rslt[name] = self._byte_chunk[jb, :].view(dtype=self.byte_order + "d")

(6504, 0)

In [10]:
df_net

,AID,SIZE,IDGX2,ODGX2,NOUTNOM,TAB113,BCENT10X,REACH,REACH3,IGDMEAN,...,SS312,SEG1RCE5,SRCE51,SRCE52,SRCE53,SRCE54,SRCE55,SEG1S2,SS20,SS21
0,b'57100270',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,b'57101310',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b'57103171',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,b'57103869',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,b'57104553',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6499,b'99719930',93.0,2.0,6.0,4.0,0.0,0.969996,79.0,33.0,3.670886,...,NaN,0.115300,NaN,1.038728,NaN,NaN,0.816393,0.283090,1.299527,1.250233
6500,b'99719939',93.0,3.0,3.0,1.0,0.0,0.469026,79.0,38.0,3.531646,...,NaN,0.115300,NaN,1.038728,NaN,NaN,0.816393,0.283090,1.299527,1.250233
6501,b'99719970',191.0,3.0,2.0,2.0,0.0,0.263245,148.0,27.0,5.506757,...,NaN,-0.007926,0.991893,NaN,0.683983,NaN,1.006675,0.289061,1.354670,1.228190
6502,b'99719976',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6503,b'99719978',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pd.read_sas(data_dir + 'w1network_fmt_data.sas7bdat')

,FMTNAME,START,END,LABEL,MIN,MAX,DEFAULT,LENGTH,FUZZ,PREFIX,...,FILL,NOEDIT,TYPE,SEXCL,EEXCL,HLO,DECSEP,DIG3SEP,DATATYPE,LANGUAGE
0,b'BFFRECBF',b' 0',b' 0',"b""(0) Ego's female best friend didn't reciproc...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
1,b'BFFRECBF',b' 1',b' 1',"b""(1) Ego's female best friend reciprocated as...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
2,b'BFFRECIP',b' 0',b' 0',"b""(0) Ego's female best friend didnt reciproca...",1.0,64.0,64.0,64.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
3,b'BFFRECIP',b' 1',b' 1',"b""(1) Ego's female best friend reciprocated fr...",1.0,64.0,64.0,64.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
4,b'BMFRECBF',b' 0',b' 0',"b""(0) Ego's best male friend didn't reciprocat...",1.0,60.0,60.0,60.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
5,b'BMFRECBF',b' 1',b' 1',"b""(1) Ego's best male friend reciprocated as b...",1.0,60.0,60.0,60.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
6,b'BMFRECIP',b' 0',b' 0',"b""(0) Ego's best male friend didnt reciprocate...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
7,b'BMFRECIP',b' 1',b' 1',"b""(1) Ego's best male friend reciprocated frie...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
8,b'HAVEBFF',b' 0',b' 0',"b""(0) Ego didn't nominate a female best friend""",1.0,44.0,44.0,44.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
9,b'HAVEBFF',b' 1',b' 1',b'(1) Ego nominiated a female best friend',1.0,44.0,44.0,44.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
10,b'HAVEBMF',b' 0',b' 0',"b""(0) Ego didn't nominate a male best friend""",1.0,42.0,42.0,42.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
11,b'HAVEBMF',b' 1',b' 1',b'(1) Ego nominiated a male best friend',1.0,42.0,42.0,42.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN

In [11]:
pd.read_sas(data_dir + 'w1network_format.sas7bcat')

ValueError: unable to infer format of SAS file

In [13]:
pd.read_sas(data_dir + 'w1network_fmt_data.sas7bdat')

,FMTNAME,START,END,LABEL,MIN,MAX,DEFAULT,LENGTH,FUZZ,PREFIX,...,FILL,NOEDIT,TYPE,SEXCL,EEXCL,HLO,DECSEP,DIG3SEP,DATATYPE,LANGUAGE
0,b'BFFRECBF',b' 0',b' 0',"b""(0) Ego's female best friend didn't reciproc...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
1,b'BFFRECBF',b' 1',b' 1',"b""(1) Ego's female best friend reciprocated as...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
2,b'BFFRECIP',b' 0',b' 0',"b""(0) Ego's female best friend didnt reciproca...",1.0,64.0,64.0,64.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
3,b'BFFRECIP',b' 1',b' 1',"b""(1) Ego's female best friend reciprocated fr...",1.0,64.0,64.0,64.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
4,b'BMFRECBF',b' 0',b' 0',"b""(0) Ego's best male friend didn't reciprocat...",1.0,60.0,60.0,60.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
5,b'BMFRECBF',b' 1',b' 1',"b""(1) Ego's best male friend reciprocated as b...",1.0,60.0,60.0,60.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
6,b'BMFRECIP',b' 0',b' 0',"b""(0) Ego's best male friend didnt reciprocate...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
7,b'BMFRECIP',b' 1',b' 1',"b""(1) Ego's best male friend reciprocated frie...",1.0,62.0,62.0,62.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
8,b'HAVEBFF',b' 0',b' 0',"b""(0) Ego didn't nominate a female best friend""",1.0,44.0,44.0,44.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
9,b'HAVEBFF',b' 1',b' 1',b'(1) Ego nominiated a female best friend',1.0,44.0,44.0,44.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
10,b'HAVEBMF',b' 0',b' 0',"b""(0) Ego didn't nominate a male best friend""",1.0,42.0,42.0,42.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN
11,b'HAVEBMF',b' 1',b' 1',b'(1) Ego nominiated a male best friend',1.0,42.0,42.0,42.0,1.000000e-12,NaN,...,NaN,0.0,b'N',b'N',b'N',NaN,NaN,NaN,NaN,NaN